<?php
$less_user_variables = array(
	"bodyBackground" => array(
		"value" => "#ffffff",
		"description" => __( "Body background", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "color",
	),
	"textColor" => array(
		"value"  => "#4d4d4d",
		"description" => __( "Text color", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "color",
	),
	"textEmboss" => array(
		"value"  => "#ffffff",
		"description" => __( "Text emboss", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "color",
	),
	"linkColor" => array(
		"value"  => "#507295",
		"description" => __( "Link", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "color",
	),
	"linkColorHover" => array(
		"value"  => "#354c63",
		"description" => __( "Link (hover)", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "color",
	),
	"baseFontFamily" => array(
		"value"  => "\"Helvetica Neue\", Helvetica, Arial, sans-serif",
		"description" => __( "Base font", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "font",
	),
	"baseFontSize" => array(
		"value"  => "13px",
		"description" => __( "Base font size", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "size",
	),
	"tableBackground" => array(
		"value"  => "#ffffff",
		"description" => __( "Table background", AI1EC_PLUGIN_NAME ),
		"tab" => "table",
		"type" => "color",
	),
	"tableLabelBackground" => array(
		"value"  => "#f5f5f5",
		"description" => __( "Table header background", AI1EC_PLUGIN_NAME ),
		"tab" => "table",
		"type" => "color",
	),
	"tableLabelText" => array(
		"value"  => "#9e9e9e",
		"description" => __( "Table header text", AI1EC_PLUGIN_NAME ),
		"tab" => "table",
		"type" => "color",
	),
	"btnBackground" => array(
		"value"  => "#ffffff",
		"description" => __( "Button background", AI1EC_PLUGIN_NAME ),
		"tab" => "buttons",
		"type" => "color",
	),
	"btnBackgroundHighlight" => array(
		"value"  => "#e6e6e6",
		"description" => __( "Button background shading", AI1EC_PLUGIN_NAME ),
		"tab" => "buttons",
		"type" => "color",
	),
	"btnBorder" => array(
		"value"  => "#d9d9d9",
		"description" => __( "Button border", AI1EC_PLUGIN_NAME ),
		"tab" => "buttons",
		"type" => "color",
	),
	"btnTextColor" => array(
		"value"  => "#333333",
		"description" => __( "Button text", AI1EC_PLUGIN_NAME ),
		"tab" => "buttons",
		"type" => "color",
	),
	"btnTextHover" => array(
		"value"  => "#1a1a1a",
		"description" => __( "Button text (hover)", AI1EC_PLUGIN_NAME ),
		"tab" => "buttons",
		"type" => "color",
	),
	"btnPrimaryBackground" => array(
		"value"  => "#62c462",
		"description" => __( "Button background (primary buttons)", AI1EC_PLUGIN_NAME ),
		"tab" => "buttons",
		"type" => "color",
	),
	"btnPrimaryBackgroundHighlight" => array(
		"value"  => "#51a351",
		"description" => __( "Button background shading (primary buttons)", AI1EC_PLUGIN_NAME ),
		"tab" => "buttons",
		"type" => "color",
	),
	"inputText" => array(
		"value"  => "#555",
		"description" => __( "Input field text", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"inputBackground" => array(
		"value"  => "#ffffff",
		"description" => __( "Input field background", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"inputBorder" => array(
		"value"  => "#cccccc",
		"description" => __( "Input field border", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"inputBorderFocus" => array(
		"value"  => "rgba(82,168,236,0.8)",
		"description" => __( "Input field border (focus)", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"inputDisabledBackground" => array(
		"value"  => "#eeeeee",
		"description" => __( "Input field background (disabled)", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"labelColor" => array(
		"value"  => "#aaaaaa",
		"description" => __( "Field label", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"dropdownBackground" => array(
		"value"  => "#ffffff",
		"description" => __( "Dropdown list background", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"dropdownBorder" => array(
		"value"  => "rgba(0,0,0,0.2)",
		"description" => __( "Dropdown list border", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"dropdownLinkColor" => array(
		"value"  => "#666666",
		"description" => __( "List item text", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"dropdownLinkColorHover" => array(
		"value"  => "#000000",
		"description" => __( "List item text (active/hover)", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"dropdownLinkBackgroundHover" => array(
		"value"  => "#e0efff",
		"description" => __( "List item background (active/hover)", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"placeholderText" => array(
		"value" => "#999999",
		"description" => __( "Input field placeholder text", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"calendarTitle" => array(
		"value"  => "#9e9e9e",
		"description" => __( "Calendar title", AI1EC_PLUGIN_NAME ),
		"tab" => "calendar",
		"type" => "color",
	),
	"todayColor" => array(
		"value"  => "#ffffdd",
		"description" => __( "Today color", AI1EC_PLUGIN_NAME ),
		"tab" => "calendar",
		"type" => "color",
	),
	"alldayBadgeHighlight" => array(
		"value"  => "#c4ccd4",
		"description" => __( "All-day badge highlight", AI1EC_PLUGIN_NAME ),
		"tab" => "calendar",
		"type" => "color",
	),
	"alldayBadgeGradientTop" => array(
		"value"  => "#7b8c9d",
		"description" => __( "All-day badge gradient top", AI1EC_PLUGIN_NAME ),
		"tab" => "calendar",
		"type" => "color",
	),
	"alldayBadgeGradientMiddle" => array(
		"value"  => "#566675",
		"description" => __( "All-day badge gradient middle", AI1EC_PLUGIN_NAME ),
		"tab" => "calendar",
		"type" => "color",
	),
	"alldayBadgeGradientBottom" => array(
		"value"  => "#3f4a55",
		"description" => __( "All-day badge gradient bottom", AI1EC_PLUGIN_NAME ),
		"tab" => "calendar",
		"type" => "color",
	),
	"alldayBadgeShadow" => array(
		"value"  => "rgba(0,0,0,0.08)",
		"description" => __( "All-day badge drop shadow", AI1EC_PLUGIN_NAME ),
		"tab" => "calendar",
		"type" => "color",
	),
	"eventImageShadow" => array(
		"value"  => "rgba(0,0,0,0.4)",
		"description" => __( "Event image shadow", AI1EC_PLUGIN_NAME ),
		"tab" => "calendar",
		"type" => "color",
	),
	"titleFontFamily" => array(
		"value"  => "\"League Gothic\", Impact, \"Arial Black\", Arial, sans-serif",
		"description" => __( "Title font", AI1EC_PLUGIN_NAME ),
		"tab" => "posterboard",
		"type" => "font",
	),
	"titleFontSize" => array(
		"value"  => "30px",
		"description" => __( "Title font size", AI1EC_PLUGIN_NAME ),
		"tab" => "posterboard",
		"type" => "size",
	),
	"posterboardMainBg" => array(
		"value"  => "rgba(255, 255, 255, 0)",
		"description" => __( "Main background", AI1EC_PLUGIN_NAME ),
		"tab" => "posterboard",
		"type" => "color",
	),
	"posterboardTileBg" => array(
		"value"  => "#fff9f0",
		"description" => __( "Tile background", AI1EC_PLUGIN_NAME ),
		"tab" => "posterboard",
		"type" => "color",
	),
	"posterboardFooterBg" => array(
		"value"  => "#f6f1ea",
		"description" => __( "Tile footer background", AI1EC_PLUGIN_NAME ),
		"tab" => "posterboard",
		"type" => "color",
	),
	"posterboardTileBorder" => array(
		"value"  => "#fff9f0",
		"description" => __( "Tile border", AI1EC_PLUGIN_NAME ),
		"tab" => "posterboard",
		"type" => "color",
	),
	"posterboardTileShadow" => array(
		"value"  => "rgba(0,0,0,0.4)",
		"description" => __( "Tile shadow", AI1EC_PLUGIN_NAME ),
		"tab" => "posterboard",
		"type" => "color",
	),
	"posterboardImageBorder" => array(
		"value"  => "rgba(0,0,0,0)",
		"description" => __( "Image border", AI1EC_PLUGIN_NAME ),
		"tab" => "posterboard",
		"type" => "color",
	),
	"posterboardImagePadding" => array(
		"value"  => "#fff",
		"description" => __( "Image padding color", AI1EC_PLUGIN_NAME ),
		"tab" => "posterboard",
		"type" => "color",
	),
	"posterboardImagePaddingWidth" => array(
		"value"  => "8px",
		"description" => __( "Image padding width", AI1EC_PLUGIN_NAME ),
		"tab" => "posterboard",
		"type" => "size",
	),
	"posterboardDateTitleText" => array(
		"value"  => "#ffffff",
		"description" => __( "Date title text", AI1EC_PLUGIN_NAME ),
		"tab" => "posterboard",
		"type" => "color",
	),
	"streamEventBorder" => array(
		"value"  => "#cccccc",
		"description" => __( "Stream view event border", AI1EC_PLUGIN_NAME ),
		"tab" => "stream",
		"type" => "color",
	),
	"streamEventBackground" => array(
		"value"  => "#ffffff",
		"description" => __( "Stream view event background", AI1EC_PLUGIN_NAME ),
		"tab" => "stream",
		"type" => "color",
	),
	"streamDateTitleText" => array(
		"value"  => "#ffffff",
		"description" => __( "Stream view date divider text", AI1EC_PLUGIN_NAME ),
		"tab" => "stream",
		"type" => "color",
	),
	"streamDateTitleBackground" => array(
		"value"  => "#c4c4c4",
		"description" => __( "Stream view date divider background", AI1EC_PLUGIN_NAME ),
		"tab" => "stream",
		"type" => "color",
	),
	"eventDefaultColor" => array(
		"value"  => "#507295",
		"description" => __( "Event default color", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventDefaultColorHover" => array(
		"value"  => "#354c63",
		"description" => __( "Event default color (hover)", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventStubAllDayText" => array(
		"value"  => "#ffffff",
		"description" => __( "All-day/multi-day event stub text", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventStubAllDayTextShadow" => array(
		"value"  => "rgba(0,0,0,0.4)",
		"description" => __( "All-day/multi-day event stub text shadow", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventBorder" => array(
		"value"  => "#ccc",
		"description" => __( "Event border", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventBackground" => array(
		"value"  => "#ffffff",
		"description" => __( "Event background", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventTimeBackground" => array(
		"value"  => "#eee",
		"description" => __( "Event time background", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventText" => array(
		"value"  => "#333333",
		"description" => __( "Event text", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"monthViewDateBackground" => array(
		"value"  => "#eaf4ff",
		"description" => __( "Month view date background", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"dayViewNowMarkerColor" => array(
		"value"  => "#f2c539",
		"description" => __( "Week/day view now marker", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"agendaDateTitleBorder" => array(
		"value"  => "#617284",
		"description" => __( "Date title border", AI1EC_PLUGIN_NAME ),
		"tab" => "agenda",
		"type" => "color",
	),
	"agendaDateTitleBackground" => array(
		"value"  => "#ffffff",
		"description" => __( "Date title background", AI1EC_PLUGIN_NAME ),
		"tab" => "agenda",
		"type" => "color",
	),
	"agendaDateTitleMonthText" => array(
		"value"  => "#ffffff",
		"description" => __( "Date title month text", AI1EC_PLUGIN_NAME ),
		"tab" => "agenda",
		"type" => "color",
	),
	"agendaDateBackground" => array(
		"value"  => "#f2f2f2",
		"description" => __( "Date background", AI1EC_PLUGIN_NAME ),
		"tab" => "agenda",
		"type" => "color",
	),
	"agendaTodayBackground" => array(
		"value"  => "#f4f4bf",
		"description" => __( "Today background", AI1EC_PLUGIN_NAME ),
		"tab" => "agenda",
		"type" => "color",
	),
);
